import { ServiceItem, ProjectItem, ServiceAreaItem, FAQItem, TestimonialItem } from '@/types';

export const COMPANY_CONFIG = {
  name: 'Calgary Home Framing',
  legalName: 'Calgary Home Framing Ltd.',
  phone: '(403) 612-9421',
  phoneRaw: '+14036129421',
  email: 'quotes@calgaryhomeframing.ca',
  supportEmail: 'info@calgaryhomeframing.ca',
  addressPlaceholder: 'Calgary, Alberta, Canada',
  serviceRegion: 'Calgary, Airdrie, Cochrane, Chestermere, Okotoks & Foothills County',
  hours: 'Mon – Fri: 7:00 AM – 5:30 PM | Sat: By Appointment',
  licensePlaceholder: 'City of Calgary Licensed Contractor • WCB Alberta Account Active • $5M Commercial General Liability Insured',
  ownerPlaceholder: 'Master Framer & Lead Site Superintendent',
  socials: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    googleBusiness: 'https://google.com/maps',
  },
  meta: {
    siteUrl: 'https://calgaryhomeframing.ca',
    siteName: 'Calgary Home Framing',
    defaultTitle: 'Residential Home Framing Contractor Calgary | Custom Builds & Additions',
    defaultDescription: 'Professional residential framing contractor in Calgary & surrounding areas. Specializing in new homes, custom builds, basements, garages, additions, and structural framing.',
  },
};

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: '1',
    author: 'Dave Miller',
    role: 'General Contractor',
    location: 'Altadore, Calgary',
    projectType: '3-Storey Infill Framing',
    rating: 5,
    highlight: 'Passed City Inspection 1st Walkthrough',
    quote: 'Calgary Home Framing framed our 3-storey infill in Altadore with razor-sharp accuracy. Subfloors were dead level, exterior walls were plumb, and city framing inspection passed on the first walkthrough with zero notes. Our drywallers and cabinet installers thanked us.',
  },
  {
    id: '2',
    author: 'Sarah & Mark Thompson',
    role: 'Homeowners',
    location: 'Mahogany Lake, Calgary',
    projectType: 'Basement Suite & Garage Addition',
    rating: 5,
    highlight: 'Clean Jobsite & Daily Milestone Updates',
    quote: 'We hired Calgary Home Framing for our legal secondary suite development and detached garage. They kept a clean jobsite every evening, communicated daily milestones, and completed the framing 3 days ahead of schedule.',
  },
  {
    id: '3',
    author: 'Elena Rostova',
    role: 'Architectural Project Lead',
    location: 'Aspen Woods Estate, Calgary',
    projectType: 'Custom 4,500 sq.ft. Timber Build',
    rating: 5,
    highlight: 'Mastery of Complex Timber Engineering',
    quote: 'Their understanding of engineered timber, heavy LVL beams, and complex vaulted cathedral rooflines is top-tier. They caught two architectural drawing discrepancies before cutting a single board, saving our build weeks.',
  },
  {
    id: '4',
    author: 'Kevin Bradley',
    role: 'Renovation Contractor',
    location: 'Mount Pleasant, Calgary',
    projectType: 'Load-Bearing Wall Removal & Flush LVL',
    rating: 5,
    highlight: 'Flawless Structural Shoring',
    quote: 'Removed two load-bearing walls and installed a 22-foot flush LVL beam. Systematic shoring, zero drywall settlement on the upper floor, and structural engineer sign-off was immediate. They are our go-to framing crew.',
  },
];

export const TRUST_POINTS = [
  {
    title: 'Quality Craftsmanship',
    description: 'Square, plumb, and true timber framing built strictly to Alberta Building Code specifications.',
    icon: 'Hammer',
  },
  {
    title: 'Reliable Communication',
    description: 'Clear schedule updates, direct coordination with site supers and homeowners, and zero guesswork.',
    icon: 'MessageSquare',
  },
  {
    title: 'Professional Worksites',
    description: 'Clean, organized framing sites, safety-focused crew protocols, and efficient material handling.',
    icon: 'HardHat',
  },
  {
    title: 'Residential Expertise',
    description: 'Dedicated focus on residential wood framing — from complex architecturals to efficient spec homes.',
    icon: 'Home',
  },
];

export const PROCESS_STEPS = [
  {
    number: '01',
    title: 'Tell Us About Your Project',
    description: 'Submit your project details, location, desired timeline, and architectural drawings through our quote form or direct call.',
  },
  {
    number: '02',
    title: 'Scope & Plan Review',
    description: 'We perform a detailed takeoff of your architectural blueprints, structural engineering notes, and site conditions.',
  },
  {
    number: '03',
    title: 'Clear Quote & Scheduling',
    description: 'Receive a transparent, itemized framing estimate with confirmed crew scheduling and timeline projections.',
  },
  {
    number: '04',
    title: 'Precision Framing Execution',
    description: 'Our experienced framing crew builds your project according to engineered specifications, ready for mechanicals and inspections.',
  },
];

export const SERVICES_DATA: ServiceItem[] = [
  {
    slug: 'new-home-framing',
    title: 'New Home Framing',
    shortDescription: 'Complete structural timber framing packages for new residential single-family, semi-detached, and duplex construction across Calgary.',
    fullDescription: 'Our new home framing service delivers complete, turn-key structural framing packages for residential builders, general contractors, and private homeowners. From sill plates and floor joist systems to precision exterior 2x6 walls, interior partition layouts, and roof truss package erection, we frame every structure square, plumb, and code-compliant.',
    image: '/images/service-new-home.jpg',
    features: [
      'Complete subfloor and floor joist installations (I-joists & open web trusses)',
      'Exterior 2x6 framing with advanced thermal break and shear-wall nailing schedules',
      'Interior partition framing ready for mechanical trades and drywall',
      'Engineered roof truss setting, gable bracing, and roof deck sheathing',
      'Window and exterior door rough openings per manufacturer rough specs',
      'Coordination with city framing inspectors and structural engineers',
    ],
    scope: [
      'Foundation anchor bolt verification & sill gasket installation',
      'Main floor framing & OSB / plywood tongue-and-groove subfloor glue & screw',
      'Second-storey wall assemblies & bearing partition load paths',
      'Truss package erection, hurricane ties, and temporary bracing',
      'Exterior wall sheathing & roof deck installation with H-clips',
    ],
    deliverables: [
      'Framed structure ready for rough-in trades (HVAC, plumbing, electrical)',
      'Completed framing checklist verified against architectural drawings',
      'Jobsite broom-cleaned and lumber scraps neatly sorted',
    ],
    idealFor: 'Custom home builders, general contractors, and homeowners managing a new residential build in Calgary and surrounding areas.',
    metaTitle: 'New Home Framing Contractor Calgary | Residential Construction',
    metaDescription: 'Expert new home framing in Calgary, AB. Structural framing packages for single-family homes, duplexes, and infills. Request your framing quote today.',
  },
  {
    slug: 'custom-home-framing',
    title: 'Custom Home Framing',
    shortDescription: 'Detailed structural framing for architecturally distinct custom homes, vaulted cathedral ceilings, clerestories, and complex timber details.',
    fullDescription: 'Custom homes demand a higher degree of carpentry precision and blueprint interpretation. We specialize in framing complex architectural designs featuring vaulted cathedral ceilings, multi-pitch rooflines, large floor-to-ceiling window openings, heavy timber accents, and custom structural steel-to-wood connections.',
    image: '/images/service-custom-home.jpg',
    features: [
      'Precision framing for intricate architectural blueprints and custom angles',
      'Vaulted, coffered, and barrel ceiling assemblies',
      'Steel beam and post wood wrapping / integration',
      'Complex multi-gable and shed roofline stick-framing',
      'High-span openings for custom multi-slide patio doors',
      'Continuous load path verification for open-concept floorplans',
    ],
    scope: [
      'Architectural blueprint & engineering package pre-construction review',
      'Laser-aligned layout and custom angle layout execution',
      'Installation of heavy engineered structural wood products (LVL, PSL, Glulam)',
      'Custom dormers, cantilevered overhangs, and architectural feature walls',
    ],
    deliverables: [
      'Masterfully framed custom residence ready for luxury finishing',
      'Precision tolerances on high walls and ceiling planes',
    ],
    idealFor: 'Architects, bespoke custom builders, and homeowners building one-of-a-kind residences in Calgary, Springbank, and foothills acreages.',
    metaTitle: 'Custom Home Framing Calgary | Luxury Residential Carpentry',
    metaDescription: 'Precision custom home framing contractor in Calgary. Specialized in architectural roofs, vaulted ceilings, and complex engineered timber designs.',
  },
  {
    slug: 'basement-framing',
    title: 'Basement Framing',
    shortDescription: 'Professional basement development framing, perimeter frost walls, mechanical bulkheads, subfloor prep, and bedroom egress framing.',
    fullDescription: 'Transform unfinished concrete basements into comfortable, code-compliant living spaces. We frame basement developments with attention to straight walls, clean HVAC duct bulkheads, bathroom plumbing accommodations, soundproofing wall channels, and proper egress window rough openings.',
    image: '/images/service-basement.jpg',
    features: [
      'Treated bottom plate installation with moisture barrier gasket',
      'Tight, square perimeter frost wall framing with insulation clearance',
      'Clean low-profile bulkheads around ductwork, beams, and plumbing stacks',
      'Legal basement suite layout framing and fire-separation assemblies',
      'Egress window enlargement and framing support',
      'Bathroom, wet bar, mechanical room, and home theatre partitions',
    ],
    scope: [
      'Laser-level perimeter layout and concrete moisture assessment',
      'Fastening bottom plates with powder-actuated fasteners or concrete screws',
      'Precision framing of drop ceilings and mechanical enclosures',
      'Doorway and pocket door framing with square tolerances',
    ],
    deliverables: [
      'Drywall-ready basement framing ready for electrical, plumbing, and HVAC rough-ins',
      'Adherence to City of Calgary basement development code requirements',
    ],
    idealFor: 'Homeowners developing basements, secondary suite investors, and basement renovation contractors.',
    metaTitle: 'Basement Framing Calgary | Basement Development Framing Contractors',
    metaDescription: 'Professional basement framing in Calgary. Perimeter walls, bulkheads, legal suites, and egress window framing. Get a free basement estimate.',
  },
  {
    slug: 'garage-framing',
    title: 'Garage Framing',
    shortDescription: 'Attached and detached residential garage framing, oversized garage packages, workshops, carriage suites, and high-clearance door openings.',
    fullDescription: 'From standard two-car detached garages to oversized heated workshops and carriage suites, our crew builds rigid, weatherproof garage framing packages designed to withstand Calgary winter wind and snow loads. We handle slab layout, wall stud erection, structural door headers, and roof truss packages.',
    image: '/images/service-garage.jpg',
    features: [
      'Detached 2-car, 3-car, and tandem garage structural framing',
      'Oversized door headers for 8ft, 9ft, and 10ft high overhead garage doors',
      'Engineered roof truss installation with attic storage capacity options',
      'Carriage suite / garden suite second-storey framing',
      'Man-door and window framing per site plan',
      'Exterior OSB wall sheathing and roof deck sheathing',
    ],
    scope: [
      'Concrete slab layout check and sill plate anchoring',
      '2x4 or 2x6 exterior wall construction at 16” on-center',
      'Truss setting, hurricane strapping, and gable end bracing',
      'Roof sheathing with expansion gaps and fascia backing',
    ],
    deliverables: [
      'Complete weatherproof framing structure ready for siding, roofing, and overhead door install',
    ],
    idealFor: 'Homeowners needing detached garages, laneway garden suites, and builders executing suburban garage packages.',
    metaTitle: 'Garage Framing Calgary | Detached & Attached Garage Builders',
    metaDescription: 'Calgary garage framing specialists. Quality timber framing for detached 2-car garages, workshops, and carriage suites. Free quote online.',
  },
  {
    slug: 'home-additions',
    title: 'Home Additions',
    shortDescription: 'Structural framing for second-storey additions, main-floor rear bump-outs, sunrooms, and seamless roofline and foundation tie-ins.',
    fullDescription: 'Adding square footage to an existing house requires careful structural planning and carpentry finesse. We handle home addition framing by tying new floor systems, load-bearing walls, and roof trusses seamlessly into your existing home’s structure while protecting the existing envelope.',
    image: '/images/service-addition.jpg',
    features: [
      'Second-storey addition framing over existing main floors',
      'Rear and side main-floor expansion framing',
      'Seamless roof tie-ins (valley framing, dormers, and rafters)',
      'Structural foundation-to-wood connection tie-ins',
      'Weather-conscious fast framing to protect open structures',
      'Coordination with engineer structural connection details',
    ],
    scope: [
      'Selective structural tie-in preparation',
      'Framing of new addition floor joist systems and bearing plates',
      'Exterior wall framing matching existing ceiling heights',
      'Roof integration and water-shedding valley carpentry',
    ],
    deliverables: [
      'Rigid, weather-tight addition framing integrated with existing home structure',
      'Passed municipal structural inspection milestone',
    ],
    idealFor: 'Homeowners expanding their living space and general contractors executing residential extensions.',
    metaTitle: 'Home Addition Framing Calgary | Second Storey & Extension Framing',
    metaDescription: 'Calgary residential home addition framing. Second-storey extensions, bump-outs, and structural roof tie-ins. Contact our framing crew today.',
  },
  {
    slug: 'renovation-framing',
    title: 'Renovation Framing',
    shortDescription: 'Structural wall removal, temporary shoring, engineered LVL beam installations, and interior layout reconfiguration for open-concept renovations.',
    fullDescription: 'Open-concept living requires removing interior walls without compromising the structural integrity of your home. We provide precision renovation framing, including temporary load-bearing shoring, engineered LVL/steel beam insertion, flush-beam ceiling installations, and doorway/window reconfigurations.',
    image: '/images/service-renovation.jpg',
    features: [
      'Load-bearing wall removal with temporary shoring towers',
      'Engineered LVL (Laminated Veneer Lumber) beam installations',
      'Flush-beam framing for uninterrupted flat ceiling lines',
      'Point load transfer down to basement foundation pads',
      'Window-to-patio door enlargement structural headers',
      'Interior partition redesign and pocket door installations',
    ],
    scope: [
      'Review of engineer beam sizing and point load specifications',
      'Erection of temporary load-bearing shoring walls with screw jacks',
      'Removal of bearing studs and placement of multi-ply LVL beams',
      'Installation of engineered steel post supports and Simpson hold-down hardware',
    ],
    deliverables: [
      'Safe, engineered structural beam installation ready for drywall wrap',
      'Open-concept floorplan achieved with complete structural peace of mind',
    ],
    idealFor: 'Interior renovators, kitchen remodelers, and homeowners modernizing older Calgary layouts.',
    metaTitle: 'Renovation Framing Calgary | Load Bearing Wall Removal & LVL Beams',
    metaDescription: 'Calgary renovation framing experts. Safe load-bearing wall removal, engineered LVL beam installation, and open-concept structural carpentry.',
  },
  {
    slug: 'structural-framing',
    title: 'Structural Framing',
    shortDescription: 'Heavy-duty engineered floor systems, complex roof truss packages, post-and-beam connections, and critical load-path carpentry.',
    fullDescription: 'The structural skeleton of any building determines its longevity, floor rigidity, and resistance to environmental loads. Our structural framing service focuses on high-capacity engineered wood products, complex roof truss layouts, seismic/wind tie-downs, and heavy load transfers.',
    image: '/images/service-structural.jpg',
    features: [
      'Engineered floor system installations (TJI I-joists, Open Web, Glulam)',
      'Heavy timber and post-and-beam structural connections',
      'High-span roof truss packages with complex valley and hip sets',
      'Simpson Strong-Tie hardware, hold-downs, and hurricane clips',
      'Point load alignment from roof trusses down to foundation footings',
      'Strict adherence to engineering schedules and manufacturer specifications',
    ],
    scope: [
      'Detailed verification of engineering drawings and load paths',
      'Laser-guided leveling of beams and bearing plates',
      'Subfloor nailing and adhesive fastening to prevent squeaks',
      'Complete structural bracing and shear wall fastening schedules',
    ],
    deliverables: [
      'Engineered structural timber assembly built to the highest trade tolerances',
    ],
    idealFor: 'Builders and general contractors seeking reliable structural framing subcontractors for complex residential scopes.',
    metaTitle: 'Structural Framing Contractors Calgary | Engineered Timber Systems',
    metaDescription: 'Engineered residential structural framing in Calgary. Roof trusses, I-joist floor systems, and heavy timber framing. Request a proposal.',
  },
];

export const PROJECTS_DATA: ProjectItem[] = [
  {
    slug: 'modern-infill-two-storey',
    title: 'Modern Two-Storey Infill',
    location: 'Altadore / Marda Loop, Calgary, AB',
    category: 'new-home',
    categoryLabel: 'New Home Framing',
    shortDescription: 'Complete structural framing for a contemporary 2,800 sq.ft. two-storey infill home with flat and shed roof transitions and floor-to-ceiling window openings.',
    image: '/images/project-modern-infill.jpg',
    gallery: [
      '/images/project-modern-infill.jpg',
      '/images/service-new-home.jpg',
      '/images/crew-jobsite.jpg',
    ],
    specs: [
      { label: 'Project Type', value: 'New Infill Home Framing' },
      { label: 'Location', value: 'Calgary (Inner City)' },
      { label: 'Framing Duration', value: '18 On-Site Build Days' },
      { label: 'Square Footage', value: '2,800 sq.ft. + Basement' },
      { label: 'Key Feature', value: 'Mixed Shed & Flat Rooflines' },
    ],
    overview: 'This project involved complete framing for a modern architectural infill residence in an established Calgary neighborhood. The blueprint featured contemporary asymmetric shed rooflines, cantilevered upper-floor bump-outs, and expansive glazing pockets on the south elevation.',
    scopeOfWork: [
      'Foundation layout and 2x6 exterior wall framing at 16" O.C.',
      'Engineered I-joist floor systems with 3/4" tongue-and-groove glued subflooring',
      'Custom stick-framed shed roof rafters and parapet walls for modern aesthetic',
      'Installation of structural steel flitch beams for wide front living room openings',
      'Interior partition wall framing ready for high-end modern finishes',
    ],
    framingDetails: [
      'Continuous load path engineering from roof rafters to foundation sill',
      'Heavy-duty OSB shear panels with specific high-density nailing patterns',
      'Precise rough openings to accommodate custom aluminum-clad window packages',
    ],
    challenges: 'Tight urban lot with minimal site clearance and zero lot-line access on the west side, requiring coordinated crane picks and phased material staging.',
    solution: 'Pre-cut and organized lumber packages staged strictly in build order, with precision crane placement of second-floor wall and roof assemblies.',
    finalResult: 'Framed on schedule with zero municipal inspection deficiencies, providing a perfectly plumb and square canvas for mechanical trades and exterior envelope.',
  },
  {
    slug: 'custom-foothills-estate',
    title: 'Custom Foothills Timber Estate',
    location: 'Springbank / Bearspaw, Calgary Area, AB',
    category: 'custom-home',
    categoryLabel: 'Custom Home Framing',
    shortDescription: 'Bespoke 4,500 sq.ft. custom estate featuring soaring 22ft cathedral vaulted ceilings, exposed timber rafters, and multi-tier gable roof packages.',
    image: '/images/project-custom-estate.jpg',
    gallery: [
      '/images/project-custom-estate.jpg',
      '/images/service-custom-home.jpg',
      '/images/service-structural.jpg',
    ],
    specs: [
      { label: 'Project Type', value: 'Custom Estate Home Framing' },
      { label: 'Location', value: 'Springbank / Calgary West' },
      { label: 'Framing Duration', value: '28 On-Site Build Days' },
      { label: 'Square Footage', value: '4,500 sq.ft. + 3-Car Garage' },
      { label: 'Key Feature', value: '22ft Vaulted Ceilings & Heavy Timber Portico' },
    ],
    overview: 'A luxury acreage residence designed to capture sweeping views of the Alberta foothills and Rocky Mountains. The design included intricate multi-pitch roof geometry, a grand vaulted great room, and an attached 3-car garage wing with high-clearance overhead doors.',
    scopeOfWork: [
      'Heavy timber truss installation and vaulted great room stick framing',
      'Multi-ply LVL and Glulam ridge beams with concealed steel knife-plate connectors',
      'Multi-gable roof truss package with complex valley sets and eyebrow dormers',
      'High-wall balloon framing in great room with engineered wind-load bracing',
      'Complete attached three-car garage framing with 10ft door rough openings',
    ],
    framingDetails: [
      'Double top plates and engineered LVL studs on 22ft high perimeter walls',
      'Full roof deck sheathing with H-clips and hurricane tie hardware at all bearing points',
      'Integrated hidden conduit raceways for architectural lighting in exposed timber members',
    ],
    challenges: 'High wind exposure during construction on the open foothills ridge and heavy Glulam beam lifts over an expansive open foundation.',
    solution: 'Engineered temporary diagonal wind bracing throughout all phases and dedicated mobile crane picks for rapid, safe beam placement.',
    finalResult: 'A showcase custom framing execution delivered to exact architectural tolerances, creating a striking silhouette against the Rocky Mountain backdrop.',
  },
  {
    slug: 'suburban-double-garage',
    title: 'Detached Double Garage Package',
    location: 'Airdrie / North Calgary, AB',
    category: 'garage',
    categoryLabel: 'Garage Framing',
    shortDescription: 'Clean 24x26 detached residential garage framing package with engineered gable roof trusses, 16x8 overhead door header, and storage attic trusses.',
    image: '/images/service-garage.jpg',
    gallery: [
      '/images/service-garage.jpg',
      '/images/hero-calgary-framing.jpg',
    ],
    specs: [
      { label: 'Project Type', value: 'Detached Garage Framing' },
      { label: 'Location', value: 'Airdrie / Calgary Area' },
      { label: 'Dimensions', value: '24ft x 26ft' },
      { label: 'Roof Style', value: 'Engineered Gable Roof Package' },
      { label: 'Key Feature', value: 'Overhead Storage Truss Integration' },
    ],
    overview: 'Detached two-car garage build providing functional vehicle parking and upper-level storage in a suburban backyard setting.',
    scopeOfWork: [
      'Treated bottom plate anchoring to cured concrete slab with moisture barrier',
      '2x4 exterior wall framing at 16" on-center with structural corner bracing',
      'Engineered 16ft overhead door header installation',
      'Gable truss setting, bracing, and 7/16" OSB roof sheathing',
      'Fascia sub-framing and man-door / window rough openings',
    ],
    framingDetails: [
      'Precision plumb corners ensuring smooth overhead door track installation',
      'Weather-tight wall sheathing ready for housewrap and vinyl siding',
    ],
    challenges: 'Restricted rear laneway access requiring careful lumber drop-off and efficient site footprint management.',
    solution: 'Fast-paced framing completed within days with tidy jobsite cleanup.',
    finalResult: 'Solid, square garage frame ready for roofing, electrical wiring, and exterior finishing.',
  },
  {
    slug: 'inner-city-open-concept-renovation',
    title: 'Open-Concept Structural Renovation',
    location: 'Mount Pleasant, Calgary, AB',
    category: 'renovation',
    categoryLabel: 'Renovation Framing',
    shortDescription: 'Complete load-bearing interior wall removal and installation of a 22-foot flush LVL beam to create an uninterrupted open-concept living space.',
    image: '/images/service-renovation.jpg',
    gallery: [
      '/images/service-renovation.jpg',
      '/images/service-structural.jpg',
    ],
    specs: [
      { label: 'Project Type', value: 'Structural Renovation Framing' },
      { label: 'Location', value: 'Calgary (NW)' },
      { label: 'Beam Span', value: '22ft Multi-Ply LVL' },
      { label: 'Execution', value: 'Flush Ceiling Installation' },
      { label: 'Engineering', value: 'Point Load Transfer to Basement' },
    ],
    overview: 'An interior transformation of a 1970s bungalow, converting compartmentalized kitchen and living areas into a bright, contemporary great room.',
    scopeOfWork: [
      'Erection of dual temporary load-bearing shoring walls with screw jacks',
      'Removal of central 22ft bearing wall',
      'Insertion of 3-ply 14" LVL beam recessed into ceiling joist plane',
      'Installation of joist hangers on all perpendicular ceiling joists',
      'Structural post installation and basement pad point-load transfer',
    ],
    framingDetails: [
      'Precision joist cutback and laser-aligned beam elevation to prevent drywall cracking',
      'Simpson Strong-Tie structural screws and heavy-duty concealed hangers',
    ],
    challenges: 'Working within a furnished living area requiring dust mitigation and zero disruption to the roof truss load above.',
    solution: 'Systematic shoring and precise beam hoist techniques executed with zero drywall movement on the upper floor.',
    finalResult: 'Expansive, open-concept floorplan delivered with structural engineer sign-off and complete peace of mind for the homeowner.',
  },
];

export const SERVICE_AREAS_DATA: ServiceAreaItem[] = [
  {
    slug: 'calgary',
    name: 'Calgary',
    tagline: 'Premier Residential Framing Across All Calgary Quadrants',
    description: 'We provide full residential framing services across NW, SW, SE, and NE Calgary — including inner-city infill projects, suburban single-family developments, basement completions, and garage packages.',
    communities: [
      'Altadore & Marda Loop',
      'Killarney & Richmond',
      'Mount Pleasant & Tuxedo',
      'Mahogany & Seton',
      'Auburn Bay & Cranston',
      'Aspen Woods & West Springs',
      'Tuscany & Rocky Ridge',
      'Bridgeland & Renfrew',
    ],
    popularServices: [
      'New Home Infill Framing',
      'Custom Two-Storey Framing',
      'Basement Development Framing',
      'Load-Bearing Wall Removal & LVL Beams',
      'Detached Backyard Garages',
    ],
    framingConsiderations: [
      'Strict adherence to City of Calgary residential building bylaws and inspection milestones',
      'Expert management of narrow inner-city infill lots and crane staging requirements',
      'Cold-weather framing capabilities tailored for Calgary winter conditions',
    ],
    metaTitle: 'Home Framing Contractor Calgary | Residential Framers Calgary AB',
    metaDescription: 'Looking for a reliable home framing contractor in Calgary? We frame new homes, custom builds, basements, and additions across Calgary. Get a quote.',
  },
  {
    slug: 'airdrie',
    name: 'Airdrie',
    tagline: 'Reliable Framing for Airdrie New Builds, Garages & Basements',
    description: 'Serving Airdrie with professional framing services for new residential developments, detached garage packages, home additions, and basement developments in growing family neighborhoods.',
    communities: [
      'Cooper’s Crossing',
      'Bayside & Bayview',
      'Kings Heights',
      'Canals',
      'Sierra Springs',
      'Woodside',
    ],
    popularServices: [
      'Detached Garage Framing Packages',
      'Basement Suite Framing',
      'New Home Subcontract Framing',
      'Home Additions & Extensions',
    ],
    framingConsiderations: [
      'Efficient turnaround on standard and oversized residential garage packages',
      'Compliance with City of Airdrie secondary suite and basement building codes',
      'High-wind resistance framing practices for prairie lot exposure',
    ],
    metaTitle: 'Framing Contractor Airdrie AB | Residential & Garage Framing',
    metaDescription: 'Trusted framing contractor in Airdrie, Alberta. New home framing, detached garages, and basement development framing. Request your free estimate.',
  },
  {
    slug: 'cochrane',
    name: 'Cochrane',
    tagline: 'Custom Home & Acreage Framing in Cochrane & Foothills',
    description: 'From hillside custom builds in Sunset Ridge to sprawling acreage homes in the Cochrane foothills, we provide precision timber framing tailored to unique architectural requirements.',
    communities: [
      'Sunset Ridge',
      'Heritage Hills',
      'Riversong & Riviera',
      'Fireside',
      'Gleneagles',
      'Cochrane Acreages & Grand Valley',
    ],
    popularServices: [
      'Custom Timber & Estate Framing',
      'Hillside & Walkout Basement Framing',
      'Large Multi-Bay Workshop Garages',
      'Vaulted Ceiling & Rafter Stick-Framing',
    ],
    framingConsiderations: [
      'Engineered wind-load framing for Cochrane ridge and valley terrain',
      'Experience with complex walkout foundation framing and stepped pony walls',
      'Large acreage timber post-and-beam construction experience',
    ],
    metaTitle: 'Framing Contractor Cochrane AB | Custom Home & Timber Framing',
    metaDescription: 'Custom residential framing contractor in Cochrane, Alberta. Specializing in acreage estates, walkout basements, and complex architectural framing.',
  },
  {
    slug: 'chestermere',
    name: 'Chestermere',
    tagline: 'Residential Framing for Chestermere Homes, Additions & Basements',
    description: 'Delivering quality framing craftsmanship for Chestermere lakeside properties, new community developments, and spacious basement recreational suites.',
    communities: [
      'Kinniburgh',
      'Westmere',
      'Rainbow Falls',
      'The Cove',
      'Dawson’s Landing',
      'Chelsea',
    ],
    popularServices: [
      'Custom Lakefront Home Framing',
      'Basement Development & Suite Framing',
      'Attached & Detached Garages',
      'Open-Concept Structural Renovations',
    ],
    framingConsiderations: [
      'High-clearance garage framing for boat and recreational vehicle storage',
      'Moisture-conscious basement frost wall framing for lake-adjacent water tables',
      'Large span open-concept floor systems for entertaining layouts',
    ],
    metaTitle: 'Framing Contractor Chestermere AB | Residential Wood Framing',
    metaDescription: 'Expert framing contractor serving Chestermere, Alberta. Custom homes, detached garages, and basement development framing. Request a quote today.',
  },
  {
    slug: 'okotoks',
    name: 'Okotoks',
    tagline: 'Quality Residential Framing in Okotoks & Foothills County',
    description: 'Providing dependable framing crews for single-family residences, custom acreage homes, detached garages, and second-storey additions throughout Okotoks and Foothills County.',
    communities: [
      'Drake Landing',
      'Crystal Shores',
      'Cimarron',
      'Air Ranch',
      'D’Arcy & Wedderburn',
      'Foothills County Acreages',
    ],
    popularServices: [
      'New Home Construction Framing',
      'Acreage Workshop & Garage Framing',
      'Second-Storey Additions',
      'Basement Finishing Framing',
    ],
    framingConsiderations: [
      'Prairie snow-load and wind-resistant roof truss assemblies',
      'Strict quality controls ensuring fast trade turnover for plumbers and electricians',
      'Coordination with Town of Okotoks building inspections and safety codes',
    ],
    metaTitle: 'Framing Contractor Okotoks AB | Residential Framing & Additions',
    metaDescription: 'Professional home framing in Okotoks, Alberta. Quality wood framing for new homes, garages, basements, and additions. Free quote online.',
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    id: 'types-of-homes',
    question: 'What types of homes do you frame?',
    answer: 'We frame all types of residential wood-frame structures across Calgary and area. This includes single-family detached homes, custom architectural builds, semi-detached duplexes, inner-city infills, detached and attached garages, carriage houses, and second-storey additions.',
    category: 'services',
  },
  {
    id: 'homeowners-or-builders',
    question: 'Do you work with homeowners or builders?',
    answer: 'We work with both. We partner with general contractors, residential home builders, and project managers as their trusted framing subcontractor. We also work directly with homeowners managing their own custom builds, additions, or basement developments.',
    category: 'general',
  },
  {
    id: 'framing-estimates',
    question: 'Do you provide framing estimates and quotes?',
    answer: 'Yes. We provide clear, itemized framing estimates based on your architectural blueprints and structural engineering drawings. You can submit your plans through our online quote form or reach out to us directly.',
    category: 'process',
  },
  {
    id: 'work-from-plans',
    question: 'Can you work from architectural and structural plans?',
    answer: 'Yes. We build strictly according to approved architectural blueprints, structural engineering schedules, and manufacturer truss/joist layouts. We verify all bearing points, beam specifications, and rough openings against your drawings.',
    category: 'blueprints',
  },
  {
    id: 'frame-basements',
    question: 'Do you frame basements and secondary suites?',
    answer: 'Yes. We handle complete basement development framing, including perimeter frost walls with moisture protection, HVAC and plumbing bulkheads, bedroom partition walls with code-compliant egress door/window framing, and legal suite fire separation walls.',
    category: 'services',
  },
  {
    id: 'frame-garages',
    question: 'Do you frame detached and attached garages?',
    answer: 'Yes. We build complete residential garage framing packages for 2-car, 3-car, and custom workshop garages, including slab anchor fastening, high-clearance door headers, roof truss installation, and wall/roof sheathing.',
    category: 'services',
  },
  {
    id: 'home-additions',
    question: 'Do you handle home additions and structural tie-ins?',
    answer: 'Yes. We frame main-floor extensions and second-storey additions, carefully tying new floor systems, load-bearing walls, and rooflines into the existing house structure while maintaining structural integrity.',
    category: 'services',
  },
  {
    id: 'when-to-contact',
    question: 'How early should I contact a framing contractor?',
    answer: 'It is ideal to contact us as soon as your architectural drawings are being finalized or submitted for municipal permits. Early contact allows us to review the plans, provide an accurate takeoff, and reserve your project in our crew schedule.',
    category: 'process',
  },
  {
    id: 'service-areas',
    question: 'What areas around Calgary do you serve?',
    answer: 'Our core service area covers all of Calgary (NW, SW, SE, NE) as well as Airdrie, Cochrane, Chestermere, Okotoks, Bearspaw, Springbank, and surrounding Foothills County acreage communities.',
    category: 'general',
  },
  {
    id: 'quote-process-steps',
    question: 'How does the quote process work?',
    answer: 'First, you send us your project details, location, and blueprints via our online form. Next, we review the scope of work and engineering specifications. We then provide a clear, itemized quote detailing the framing scope and schedule availability.',
    category: 'process',
  },
  {
    id: 'send-building-plans',
    question: 'Can I send my building plans electronically?',
    answer: 'Yes! You can upload your PDF blueprints, architectural plans, or structural drawings directly through our online quote form or email them to our team for a fast review.',
    category: 'blueprints',
  },
  {
    id: 'framing-duration',
    question: 'How long does home framing usually take?',
    answer: 'Framing duration depends on the square footage, architectural complexity, weather conditions, and site logistics. A standard garage may take 2–4 days, a basement 2–5 days, while a full new home framing package typically ranges from 2 to 4 weeks once the foundation is cured.',
    category: 'timeline',
  },
];
